### ISSUE TITLE
TypeError: this.errorHandler is not a function

### ISSUE THREAD

**Issue by RobinStut** [Mennauu/pt-team-19-20#3]

**Comment by RobinStut** [comment]
I ran into an error when you are entering your user details, after you registered.
As soon as you submit the form without javascript, and you did not provide the form with an image, you will encouter this error:

```bash
TypeError: this.errorHandler is not a function
    at userSettings (/Users/robinstut/Desktop/Tech/pt-team-19-20/server/routes/post/userSettings.js:99:21)
    at _f12‍.r.exports.userSettings (/Users/robinstut/Desktop/Tech/pt-team-19-20/server/routes/routeHandler.js:21:38)
    at Layer.handle [as handle_request] (/Users/robinstut/Desktop/Tech/pt-team-19-20/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/robinstut/Desktop/Tech/pt-team-19-20/node_modules/express/lib/router/route.js:137:13)
    at Immediate._onImmediate (/Users/robinstut/Desktop/Tech/pt-team-19-20/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (internal/timers.js:445:19)
    at process.topLevelDomainCallback (domain.js:136:23)
```

**Comment by Mennauu** [comment]
Robin figured there was something wrong with the function `errorHandler` on the server and he was right. It's a function that's being used on the client and not on the server. Copy and paste mistake, by yours truly: me.

**Comment by Mennauu** [comment]
Robin fixed this.
